(() => {
  'use strict';
  const STORAGE_KEY = 'invoice-radar:v1';
  const today = () => new Date().toISOString().slice(0, 10);
  const addDays = (date, days) => { const d = new Date(`${date}T12:00:00`); d.setDate(d.getDate() + days); return d.toISOString().slice(0, 10); };
  const uid = () => `inv_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  const money = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value) || 0);
  const dateLabel = value => { if (!value) return 'No date'; const d = new Date(`${value}T12:00:00`); return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }); };
  const escape = value => { const div = document.createElement('div'); div.textContent = String(value ?? ''); return div.innerHTML; };
  const daysFromToday = due => Math.round((new Date(`${due}T12:00:00`) - new Date(`${today()}T12:00:00`)) / 86400000);
  const normalize = raw => ({ id: String(raw.id || uid()), client: String(raw.client || '').slice(0, 80), reference: String(raw.reference || '').slice(0, 40), amount: Math.max(0, Number(raw.amount) || 0), issueDate: String(raw.issueDate || today()).slice(0, 10), dueDate: String(raw.dueDate || today()).slice(0, 10), status: ['open', 'paid', 'paused'].includes(raw.status) ? raw.status : 'open', notes: String(raw.notes || '').slice(0, 240) });
  const validInvoice = invoice => {
    const datePattern = /^\d{4}-\d{2}-\d{2}$/;
    const issue = new Date(`${invoice.issueDate}T12:00:00`);
    const due = new Date(`${invoice.dueDate}T12:00:00`);
    return Boolean(invoice.client && invoice.reference && Number.isFinite(invoice.amount) && invoice.amount > 0 && datePattern.test(invoice.issueDate) && datePattern.test(invoice.dueDate) && !Number.isNaN(issue.getTime()) && !Number.isNaN(due.getTime()) && invoice.dueDate >= invoice.issueDate);
  };
  const demo = () => { const base = today(); return [
    normalize({ id: uid(), client: 'Northstar Studio', reference: 'INV-1042', amount: 1850, issueDate: addDays(base, -25), dueDate: addDays(base, -10), status: 'open', notes: 'Second follow-up is due.' }),
    normalize({ id: uid(), client: 'Cedar & Co.', reference: 'INV-1043', amount: 720, issueDate: addDays(base, -12), dueDate: base, status: 'open', notes: 'Due today.' }),
    normalize({ id: uid(), client: 'Juniper Workshop', reference: 'INV-1044', amount: 1250, issueDate: addDays(base, -4), dueDate: addDays(base, 10), status: 'open', notes: 'Upcoming project milestone.' }),
    normalize({ id: uid(), client: 'Sample paid invoice', reference: 'INV-1041', amount: 450, issueDate: addDays(base, -35), dueDate: addDays(base, -20), status: 'paid', notes: 'Demo completed.' })
  ]; };
  const load = () => { try { const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); return Array.isArray(parsed) ? parsed.map(normalize) : []; } catch { return []; } };
  let invoices = load();
  let activeFilter = 'open';
  let draftInvoiceId = null;
  let draftTone = 'friendly';

  const $ = selector => document.querySelector(selector);
  const list = $('#invoice-list');
  const empty = $('#empty-state');
  const form = $('#invoice-form');
  const save = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(invoices));
  const announce = message => { const toast = $('#toast'); toast.textContent = message; toast.hidden = false; window.clearTimeout(announce.timer); announce.timer = window.setTimeout(() => { toast.hidden = true; }, 2600); };

  function classification(invoice) {
    if (invoice.status === 'paid') return { key: 'paid', label: 'Paid', detail: `Paid · due ${dateLabel(invoice.dueDate)}` };
    if (invoice.status === 'paused') return { key: 'paused', label: 'Paused', detail: `Paused · due ${dateLabel(invoice.dueDate)}` };
    const delta = daysFromToday(invoice.dueDate);
    if (delta < 0) return { key: 'overdue', label: `${Math.abs(delta)}d overdue`, detail: `Due ${dateLabel(invoice.dueDate)}` };
    if (delta === 0) return { key: 'today', label: 'Due today', detail: `Due ${dateLabel(invoice.dueDate)}` };
    return { key: 'upcoming', label: `${delta}d to go`, detail: `Due ${dateLabel(invoice.dueDate)}` };
  }
  function priority(invoice) { const c = classification(invoice); return invoice.status === 'open' ? (c.key === 'overdue' ? 0 : c.key === 'today' ? 1 : 2) : 3; }
  function visibleInvoices() { return invoices.filter(i => activeFilter === 'all' || i.status === activeFilter).sort((a, b) => priority(a) - priority(b) || new Date(a.dueDate) - new Date(b.dueDate)); }
  function renderSummary() { const open = invoices.filter(i => i.status === 'open'); const paid = invoices.filter(i => i.status === 'paid'); const attention = open.filter(i => ['overdue', 'today'].includes(classification(i).key)); $('#open-balance').textContent = money(open.reduce((n, i) => n + i.amount, 0)); $('#open-count').textContent = `${open.length} open invoice${open.length === 1 ? '' : 's'}`; $('#attention-count').textContent = attention.length; $('#attention-foot').textContent = attention.length ? 'overdue or due today' : 'nothing urgent today'; $('#paid-balance').textContent = money(paid.reduce((n, i) => n + i.amount, 0)); $('#paid-count').textContent = `${paid.length} paid invoice${paid.length === 1 ? '' : 's'}`; }
  function renderList() { const visible = visibleInvoices(); $('#queue-count').textContent = visible.length; list.innerHTML = visible.map(invoice => { const c = classification(invoice); const priorityClass = c.key === 'overdue' ? ' is-priority' : c.key === 'today' ? ' is-today' : ''; const note = invoice.notes ? `<p class="invoice-note">${escape(invoice.notes)}</p>` : ''; const primary = invoice.status === 'open' ? `<button class="small-button" data-action="draft" data-id="${escape(invoice.id)}">Draft follow-up</button><button class="small-button" data-action="paid" data-id="${escape(invoice.id)}">Mark paid</button><button class="small-button" data-action="pause" data-id="${escape(invoice.id)}">Pause</button>` : `<button class="small-button" data-action="reopen" data-id="${escape(invoice.id)}">Reopen</button>`; return `<article class="invoice-card${priorityClass}"><div class="invoice-main"><div><h3 class="invoice-title">${escape(invoice.client) || 'Unlabeled client'}</h3><span class="invoice-ref">${escape(invoice.reference) || 'No reference'}</span></div><strong class="invoice-amount">${money(invoice.amount)}</strong></div><div class="invoice-meta"><span class="status-chip status-${c.key}">${escape(c.label)}</span><span class="invoice-due">${escape(c.detail)}</span></div>${note}<div class="invoice-actions">${primary}<button class="small-button" data-action="edit" data-id="${escape(invoice.id)}">Edit</button><button class="small-button danger" data-action="delete" data-id="${escape(invoice.id)}">Delete</button></div></article>`; }).join(''); const isEmpty = visible.length === 0; empty.hidden = !isEmpty; if (isEmpty) { $('#empty-title').textContent = invoices.length ? 'Nothing in this view' : 'Your queue is clear'; $('#empty-copy').textContent = invoices.length ? 'Try another filter to see the rest of your invoices.' : 'Add an invoice or load the demo data to see the workflow.'; } }
  function render() { renderSummary(); renderList(); document.querySelectorAll('.filter-button').forEach(button => button.classList.toggle('active', button.dataset.filter === activeFilter)); }
  function clearForm() { form.reset(); $('#invoice-id').value = ''; $('#issue-date').value = today(); $('#due-date').value = today(); $('#status').value = 'open'; $('#form-title').textContent = 'Add an invoice'; $('#form-mode').textContent = 'New'; $('#save-invoice').textContent = 'Add invoice'; $('#cancel-edit').hidden = true; $('#form-error').hidden = true; }
  function editInvoice(invoice) { $('#invoice-id').value = invoice.id; $('#client').value = invoice.client; $('#reference').value = invoice.reference; $('#amount').value = invoice.amount; $('#issue-date').value = invoice.issueDate; $('#due-date').value = invoice.dueDate; $('#status').value = invoice.status; $('#notes').value = invoice.notes; $('#form-title').textContent = 'Edit invoice'; $('#form-mode').textContent = 'Editing'; $('#save-invoice').textContent = 'Save changes'; $('#cancel-edit').hidden = false; $('#form-error').hidden = true; $('#client').focus(); }
  function draftText(invoice, tone) { const name = invoice.client || 'there'; const amount = money(invoice.amount); const due = dateLabel(invoice.dueDate); const opener = tone === 'friendly' ? `Hi ${name},\n\nI hope you’re well. I’m checking in on invoice ${invoice.reference || 'your invoice'} for ${amount}, which was due ${due}. Could you let me know when we can expect payment?\n\nThanks!` : tone === 'direct' ? `Hi ${name},\n\nA quick follow-up on invoice ${invoice.reference || 'your invoice'} for ${amount}, due ${due}. Please confirm the expected payment date.\n\nThank you.` : `Hi ${name},\n\nInvoice ${invoice.reference || 'your invoice'} for ${amount} was due ${due} and remains open. Please confirm the payment date or let me know if there is an issue to resolve.\n\nRegards.`; return opener; }
  function openDraft(invoice) { draftInvoiceId = invoice.id; draftTone = 'friendly'; $('#draft-title').textContent = `Draft for ${invoice.client || 'unlabeled client'}`; $('#draft-context').textContent = `${invoice.reference || 'Invoice'} · ${money(invoice.amount)} · ${classification(invoice).detail}`; $('#draft-text').value = draftText(invoice, draftTone); $('#copy-status').textContent = ''; document.querySelectorAll('.tone-button').forEach(b => b.classList.toggle('active', b.dataset.tone === draftTone)); const dialog = $('#draft-dialog'); if (typeof dialog.showModal === 'function') dialog.showModal(); else dialog.setAttribute('open', ''); }
  function closeDraft() { const dialog = $('#draft-dialog'); if (dialog.open && dialog.close) dialog.close(); else dialog.removeAttribute('open'); draftInvoiceId = null; }
  function formValues() { return normalize({ id: $('#invoice-id').value || uid(), client: $('#client').value.trim(), reference: $('#reference').value.trim(), amount: $('#amount').value, issueDate: $('#issue-date').value, dueDate: $('#due-date').value, status: $('#status').value, notes: $('#notes').value.trim() }); }

  form.addEventListener('submit', event => { event.preventDefault(); const invoice = formValues(); const error = $('#form-error'); if (!invoice.client || !invoice.reference || invoice.amount <= 0 || !invoice.issueDate || !invoice.dueDate) { error.textContent = 'Add a client label, reference, positive amount, issue date, and due date.'; error.hidden = false; return; } if (invoice.dueDate < invoice.issueDate) { error.textContent = 'Due date cannot be earlier than issue date.'; error.hidden = false; return; } const existing = invoices.some(i => i.id === invoice.id); invoices = existing ? invoices.map(i => i.id === invoice.id ? invoice : i) : [invoice, ...invoices]; save(); clearForm(); render(); announce(existing ? 'Invoice updated.' : 'Invoice added.'); });
  $('#cancel-edit').addEventListener('click', clearForm);
  $('#load-demo').addEventListener('click', () => { if (invoices.length && !window.confirm('Replace this workspace with demo data?')) return; invoices = demo(); save(); render(); announce('Demo data loaded.'); });
  $('#reset-data').addEventListener('click', () => { if (!window.confirm('Clear every invoice in this browser?')) return; invoices = []; save(); clearForm(); render(); announce('Workspace reset.'); });
  document.querySelectorAll('.filter-button').forEach(button => button.addEventListener('click', () => { activeFilter = button.dataset.filter; renderList(); document.querySelectorAll('.filter-button').forEach(b => b.classList.toggle('active', b === button)); }));
  list.addEventListener('click', event => { const button = event.target.closest('[data-action]'); if (!button) return; const invoice = invoices.find(i => i.id === button.dataset.id); if (!invoice) return; const action = button.dataset.action; if (action === 'draft') openDraft(invoice); if (action === 'edit') editInvoice(invoice); if (action === 'paid') { invoice.status = 'paid'; save(); render(); announce('Marked paid.'); } if (action === 'pause') { invoice.status = 'paused'; save(); render(); announce('Invoice paused.'); } if (action === 'reopen') { invoice.status = 'open'; save(); render(); announce('Invoice reopened.'); } if (action === 'delete' && window.confirm(`Delete ${invoice.reference || 'this invoice'}?`)) { invoices = invoices.filter(i => i.id !== invoice.id); save(); render(); announce('Invoice deleted.'); } });
  document.querySelectorAll('.tone-button').forEach(button => button.addEventListener('click', () => { draftTone = button.dataset.tone; const invoice = invoices.find(i => i.id === draftInvoiceId); if (invoice) $('#draft-text').value = draftText(invoice, draftTone); document.querySelectorAll('.tone-button').forEach(b => b.classList.toggle('active', b === button)); }));
  $('#close-dialog').addEventListener('click', closeDraft); $('#done-draft').addEventListener('click', closeDraft); $('#draft-dialog').addEventListener('cancel', closeDraft);
  $('#copy-draft').addEventListener('click', async () => { const text = $('#draft-text').value; try { await navigator.clipboard.writeText(text); $('#copy-status').textContent = 'Copied. Nothing was sent.'; } catch { $('#draft-text').focus(); $('#draft-text').select(); $('#copy-status').textContent = 'Select the text and copy manually. Nothing was sent.'; } });
  $('#export-data').addEventListener('click', () => { const blob = new Blob([JSON.stringify(invoices, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'invoice-radar-export.json'; link.click(); URL.revokeObjectURL(link.href); announce('JSON export prepared.'); });
  $('#import-data').addEventListener('change', async event => { const file = event.target.files[0]; if (!file) return; try { const parsed = JSON.parse(await file.text()); if (!Array.isArray(parsed)) throw new Error('Expected an array'); const imported = parsed.map(normalize); const valid = imported.filter(validInvoice); const rejected = imported.length - valid.length; if (rejected) announce(`${valid.length} imported; ${rejected} invalid record${rejected === 1 ? '' : 's'} skipped.`); else announce(`${valid.length} invoice${valid.length === 1 ? '' : 's'} imported.`); invoices = valid; save(); render(); } catch { announce('Import failed: choose a valid Invoice Radar JSON export.'); } event.target.value = ''; });
  clearForm(); render();
})();
